package com.spotify.music.libs.viewuri;

public final class ViewUris {
    public static final sih A = sih.a("spotify:waze:onboarding");
    public static final sih B = sih.a("spotify:waze:return");
    public static final sih C = sih.a("spotify:assisted-curation");
    public static final sih D = sih.a("spotify:assisted-curation:search");
    public static final sih E = sih.a("spotify:assisted-curation:search:album");
    public static final sih F = sih.a("spotify:assisted-curation:search:artist");
    public static final sih G = sih.a("spotify:free-tier:collection");
    public static final sih H = sih.a("spotify:free-tier:find");
    public static final sih I = sih.a("spotify:free-tier:all-songs-dialog");
    public static final sih J = sih.a("spotify:free-tier:taste-onboarding:skip-dialog");
    public static final sih K = sih.a("spotify:free-tier:taste-onboarding:artist-picker");
    public static final sih L = sih.a("spotify:free-tier:taste-onboarding:artist-search");
    public static final sih M = sih.a("spotify:free-tier:taste-onboarding:update-taste");
    public static final b N;
    public static final sih O = sih.a("spotify:data-saver-mode:settings");
    public static final sih P = sih.a("spotify:language-picker:no-skip-dialog");
    public static final sih Q = sih.a("spotify:language-picker:picker");
    public static final sih R = sih.a("spotify:internal:lyrics-full-screen");
    public static final sih S = sih.a("spotify:capped-ondemand:dialog");
    public static final sih T = sih.a("spotify:age-verification");
    public static final sih U = sih.a("spotify:config");
    public static final sih V = sih.a("spotify:now-playing");
    public static final sih W = sih.a("spotify:now-playing-bar");
    public static final sih X = sih.a("spotify:now-playing-view");
    public static final sih Y = sih.a("spotify:now-playing-view-v2");
    public static final sih Z = sih.a("spotify:queue");
    public static final sih a = sih.a("spotify");
    public static final b aA = new b("spotify:user:[^:]+");
    public static final b aB;
    public static final b aC;
    public static final b aD;
    public static final sih aE = sih.a("spotify:create-playlist");
    public static final sih aF = sih.a("spotify:rename-playlist");
    public static final b aG;
    public static final b aH;
    public static final b aI = new b("spotify:user:[^:]+:folder:[a-fA-F0-9]{16}");
    public static final b aJ = new b("spotify:album:[a-zA-Z0-9]{22}");
    public static final b aK = new b("spotify:artist:[a-zA-Z0-9]{22}(:about|:albums|:singles|:appears_on|:appears-on|:compilations|:related|:releases|:biography|:gallery|:playlists|:radio|:concert|:concerts)?");
    public static final sih aL = sih.a("spotify:internal:preferences:facebook-connect");
    public static final sih aM = sih.a("spotify:add_to_playlist");
    public static final sih aN = sih.a("spotify:disk_almost_full");
    public static final sih aO = sih.a("spotify:debug");
    public static final sih aP = sih.a("spotify:quicksilver");
    public static final sih aQ = sih.a("spotify:app:upsell");
    public static final sih aR = sih.a("spotify:upsell:premium_in_app_destination");
    public static final sih aS = sih.a("spotify:premium:activation");
    public static final sih aT = sih.a("spotify:ads:screen_saver");
    public static final sih aU = sih.a("spotify:ads:marquee");
    public static final sih aV = sih.a("spotify:ads:leave_behind_companion");
    public static final sih aW = sih.a("spotify:internal:premium_signup");
    public static final sih aX = sih.a("spotify:app:share-flow");
    public static final sih aY = sih.a("spotify:app:share:facebook-stories");
    public static final sih aZ = sih.a("spotify:app:share:instagram-stories");
    public static final sih aa = sih.a("spotify:widget");
    public static final sih ab = sih.a("spotify:app:concerts");
    public static final sih ac = sih.a("spotify:app:concerts:concert-group");
    public static final b ad = new b("spotify:concerts?:(songkick:events:)?[^:]+");
    public static final sih ae = sih.a("spotify:concerts:location-search");
    public static final sih af = sih.a("spotify:find");
    public static final b ag;
    public static final sih ah;
    public static final b ai = new b("spotify:search(:[^:]+)(:.+)");
    public static final b aj = new b("spotify:station:(artist:[a-zA-Z0-9]{22}|album:[a-zA-Z0-9]{22}|track:+[a-zA-Z0-9]{22}|genre:[^:]+|(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})|playlist:[a-zA-Z0-9]{22}|user:[^:]+:cluster:[a-zA-Z0-9]{22}|user:[^:]+:clusters|dailymix:[a-zA-Z0-9]{22})|spotify:dailymix:[a-zA-Z0-9]{22}");
    public static final b ak = new b("spotify:(artist:[a-zA-Z0-9]{22}|album:[a-zA-Z0-9]{22}|track:+[a-zA-Z0-9]{22}|genre:[^:]+|(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})|playlist:[a-zA-Z0-9]{22}|user:[^:]+:cluster:[a-zA-Z0-9]{22})");
    public static final b al = new b("spotify:station:user:[^:]+:cluster:[a-zA-Z0-9]{22}");
    public static final b am = new b("spotify:station:user:[^:]+:clusters");
    public static final b an = new b("spotify:dailymix:[a-zA-Z0-9]{22}");
    public static final sih ao = sih.a("spotify:daily-mix-hub");
    public static final sih ap = sih.a("spotify:made-for-you");
    public static final b aq = new b("spotify:station:artist:[a-zA-Z0-9]{22}");
    public static final b ar = new b("spotify:station:album:[a-zA-Z0-9]{22}");
    public static final b as = new b("spotify:station:track:+[a-zA-Z0-9]{22}");
    public static final b at = new b("spotify:station:genre:[^:]+");
    public static final b au = new b("spotify:station:((user:[^:]+:)?(playlist:[a-zA-Z0-9]{22}))");
    public static final b av = new b("spotify:radio:artist:[a-zA-Z0-9]{22}");
    public static final b aw = new b("spotify:radio:album:[a-zA-Z0-9]{22}");
    public static final b ax = new b("spotify:radio:track:+[a-zA-Z0-9]{22}");
    public static final b ay = new b("spotify:radio:genre:[^:]+");
    public static final b az = new b("spotify:radio:((user:[^:]+:)?(playlist:[a-zA-Z0-9]{22}))");
    public static final sih b = sih.a("spotify:main");
    public static final sih bA = sih.a("spotify:internal:connect-tutorial-social-listening");
    public static final sih bB = sih.a("spotify:internal:preferences:content_languages");
    public static final sih bC = sih.a("spotify:push_notification_actions");
    public static final sih bD = sih.a("spotify:internal:preferences:push_notification");
    public static final sih bE = sih.a("spotify:internal:local_files_import");
    public static final sih bF = sih.a("spotify:internal:local_files_import:folders");
    public static final sih bG = sih.a("spotify:internal:local_files_import:artists");
    public static final sih bH = sih.a("spotify:internal:local_files_import:albums");
    public static final sih bI = sih.a("spotify:internal:local_files_import:songs");
    public static final sih bJ = sih.a("spotify:internal:notification");
    public static final sih bK = sih.a("spotify:internal:preferences:storage");
    public static final sih bL = sih.a("spotify:config:account");
    public static final sih bM = sih.a("spotify:cover-image");
    public static final sih bN = sih.a("spotify:request-permissions");
    public static final sih bO = sih.a("spotify:app:app_rater");
    public static final sih bP = sih.a("spotify:media_service");
    public static final b bQ = new b("spotify:show:[a-zA-Z0-9]{22}");
    public static final sih bR = sih.a("spotify:speaker-companion:entity-feedback");
    public static final sih bS = sih.a("spotify:speaker-companion:page");
    public static final sih bT = sih.a("spotify:speaker-companion:banner");
    public static final sih bU = sih.a("spotify:wrapped:datastories");
    public static final sih bV = sih.a("spotify:voice-assistant");
    public static final sih bW = sih.a("spotify:voice-assistant:now-playing");
    public static final sih bX = sih.a("spotify:voice-assistant:dynamic_suggestion");
    public static final sih bY = sih.a("spotify:voice-assistant:onboarding");
    public static final sih bZ = sih.a("spotify:voice-assistant:error");
    public static final sih ba = sih.a("spotify:app:share:snapchat-stories");
    public static final sih bb = sih.a("spotify:collection");
    public static final b bc = new b("spotify:user:[^:]+:collection");
    public static final sih bd = sih.a("spotify:internal:collection:playlists");
    public static final sih be = sih.a("spotify:internal:collection:radio");
    public static final sih bf = sih.a("spotify:internal:collection:artists");
    public static final sih bg = sih.a("spotify:internal:collection:albums");
    public static final b bh = new b("spotify:user:[^:]+:collection:album:[a-zA-Z0-9]{22}");
    public static final b bi = new b("spotify:user:[^:]+:collection:artist:[a-zA-Z0-9]{22}");
    public static final sih bj = sih.a("spotify:internal:collection:tracks");
    public static final sih bk = sih.a("spotify:internal:collection:offlined-music");
    public static final sih bl = sih.a("spotify:collection:podcasts:following");
    public static final sih bm = sih.a("spotify:collection:podcasts:episodes");
    public static final sih bn = sih.a("spotify:collection:podcasts:downloads");
    public static final sih bo = sih.a("spotify:internal:hidden-content");
    public static final sih bp = sih.a("spotify:internal:connect-device-picker");
    public static final sih bq = sih.a("spotify:internal:connect-device-context-menu");
    public static final sih br = sih.a("spotify:internal:gaia-onboarding-popup");
    public static final sih bs = sih.a("spotify:internal:gaia-popup");
    public static final sih bt = sih.a("spotify:internal:gaia-volume");
    public static final sih bu = sih.a("spotify:internal:connect-tutorial-desktop");
    public static final sih bv = sih.a("spotify:internal:connect-tutorial-speaker");
    public static final sih bw = sih.a("spotify:internal:connect-tutorial-tv");
    public static final sih bx = sih.a("spotify:internal:connect-tutorial-gameconsole");
    public static final sih by = sih.a("spotify:internal:connect-tutorial-chromecast");
    public static final sih bz = sih.a("spotify:internal:connect-tutorial-bluetooth");
    public static final sih c = sih.a("spotify:listening-history");
    public static final sih ca = sih.a("spotify:internal:service");
    public static final sih cb = sih.a("spotify:internal:scannables");
    public static final sih cc = sih.a("spotify:socialsession:participant-list");
    public static final sih cd = sih.a("spotify:stations-promo");
    public static final sih ce = sih.a("spotify:podcastonboarding:topic-picker");
    public static final sih d = sih.a("spotify:app:radio");
    public static final sih e = sih.a("spotify:startpage");
    public static final sih f = sih.a("spotify:home");
    public static final sih g = sih.a("spotify:fullscreen-story");
    public static final sih h = sih.a("spotify:internal:running");
    public static final sih i = sih.a("spotify:app:findfriends");
    public static final sih j = sih.a("spotify:findfriends:confirm");
    public static final sih k = sih.a("spotify:genre:podcasts-page");
    public static final sih l = sih.a("spotify:charts:root");
    public static final b m = new b("spotify:charts:[^:]+");
    public static final b n = new b("spotify:(app:)?chart:[^:]+");
    public static final b o;
    public static final b p;
    public static final b q;
    public static final b r;
    public static final b s;
    public static final sih t = sih.a("spotify:internal:startpage");
    public static final b u = new b("spotify:track:+[a-zA-Z0-9]{22}");
    public static final sih v = sih.a("spotify:driving:jumpstart");
    public static final sih w = sih.a("spotify:driving:pivot");
    public static final sih x = sih.a("spotify:driving:voice");
    public static final sih y = sih.a("spotify:car:lockscreen");
    public static final sih z = sih.a("spotify:waze:optout");

    @Deprecated
    public enum SubView {
        NONE(""),
        PLACEBO_BANNER("placebo-banner"),
        CANCEL_STATE_INTERSTITIAL("cancel_state_interstitial");
        
        private final String mSubView;

        private SubView(String str) {
            this.mSubView = (String) fay.a(str);
        }

        public final String toString() {
            return this.mSubView;
        }
    }

    static {
        sih.a("spotify:navigation");
        sih.a("spotify:playlists");
        new b("spotify:home:[^:]+");
        new b("spotify:(internal:)?running:[^:]+:[^:]+");
        sih.a("spotify:app:browse");
        StringBuilder sb = new StringBuilder("spotify:genre:[^:]+");
        String str = "(:[^:]++)?";
        sb.append(fbc.a(str, 4));
        o = new b(sb.toString());
        String str2 = "spotify:(app:)?browse";
        StringBuilder sb2 = new StringBuilder(str2);
        sb2.append(fbc.a(str, 5));
        p = new b(sb2.toString());
        q = new b(str2);
        String str3 = "spotify:special:[^:]+";
        r = new b(str3);
        StringBuilder sb3 = new StringBuilder(str3);
        sb3.append(fbc.a(str, 4));
        s = new b(sb3.toString());
        sih.a("spotify:free-tier:likes");
        sih.a("spotify:free-tier:likes:songs");
        sih.a("spotify:free-tier:profile");
        String str4 = "spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})";
        N = new b(str4);
        new b(str4);
        sih.a("spotify:free-tier:data-saver:learn-more");
        sih.a("spotify:free-tier:data-saver:opt-in-status");
        sih.a("spotify:internal:nft:education:favorites-mix");
        b bVar = new b("spotify:search(:.*)?");
        ag = bVar;
        ah = bVar.a("spotify:search");
        aB = new b(str4);
        aC = new b(str4);
        aD = new b(str4);
        StringBuilder sb4 = new StringBuilder("spotify:internal:format_list_chart:(");
        sb4.append(aB);
        sb4.append(')');
        new b(sb4.toString());
        StringBuilder sb5 = new StringBuilder("spotify:internal:format_list_data_saver:(");
        sb5.append(aB);
        sb5.append(')');
        aG = new b(sb5.toString());
        StringBuilder sb6 = new StringBuilder("spotify:internal:format_list_personalized_sets:(");
        sb6.append(aB);
        sb6.append(')');
        aH = new b(sb6.toString());
        StringBuilder sb7 = new StringBuilder("spotify:internal:format_list_friends_weekly:(");
        sb7.append(aB);
        sb7.append(')');
        new b(sb7.toString());
        sih.a("spotify:intro:tos:text");
        sih.a("spotify:offline_sync_error");
        sih.a("spotify:upsell:choose_extreme_quality");
        sih.a("spotify:upsell:stuck_in_shuffle");
        sih.a("spotify:upsell:out_of_skips");
        String str5 = "spotify:upsell:no_offline";
        sih.a(str5);
        sih.a(str5);
        sih.a("spotify:upsell:no_queue");
        sih.a("spotify:upsell:trial-started");
        sih.a("spotify:upsell:trial-ended");
        sih.a("spotify:upsell:capping_reached");
        sih.a("spotify:upsell:content-unavailable");
        sih.a("spotify:ads:mobile_video_takeover");
        sih.a("spotify:ads:sponsored_session");
        sih.a("spotify:dynamic_upsell");
        sih.a("spotify:share");
        sih.a("spotify:share:missing-user");
        sih.a("spotify:licenses");
        sih.a("spotify:update");
        sih.a("spotify:internal:gaia-popup-account-linking");
        sih.a("spotify:internal:gaia-popup-dynamic-suggestion");
        sih.a("spotify:internal:preferences");
        sih.a("spotify:internal:tutorials");
        sih.a("spotify:churn_locked_state");
        sih.a("spotify:fullscreen_videoplayer");
        sih.a("spotify:wrapped:home");
        sih.a("spotify:podcastonboarding:send-topics");
    }
}
