package com.spotify.music.libs.viewuri;

public final class ViewUris {
    public static final sso A = sso.a("spotify:waze:return");
    public static final sso B = sso.a("spotify:assisted-curation");
    public static final sso C = sso.a("spotify:assisted-curation:search");
    public static final sso D = sso.a("spotify:assisted-curation:search:album");
    public static final sso E = sso.a("spotify:assisted-curation:search:artist");
    public static final sso F = sso.a("spotify:free-tier:collection");
    public static final sso G = sso.a("spotify:free-tier:find");
    public static final sso H = sso.a("spotify:free-tier:all-songs-dialog");
    public static final sso I = sso.a("spotify:free-tier:taste-onboarding:skip-dialog");
    public static final sso J = sso.a("spotify:free-tier:taste-onboarding:artist-picker");
    public static final sso K = sso.a("spotify:free-tier:taste-onboarding:artist-search");
    public static final sso L = sso.a("spotify:free-tier:taste-onboarding:update-taste");
    public static final b M;
    public static final sso N = sso.a("spotify:data-saver-mode:settings");
    public static final sso O = sso.a("spotify:language-picker:no-skip-dialog");
    public static final sso P = sso.a("spotify:language-picker:picker");
    public static final sso Q = sso.a("spotify:internal:lyrics-full-screen");
    public static final sso R = sso.a("spotify:capped-ondemand:dialog");
    public static final sso S = sso.a("spotify:age-verification");
    public static final sso T = sso.a("spotify:config");
    public static final sso U = sso.a("spotify:now-playing");
    public static final sso V = sso.a("spotify:now-playing-bar");
    public static final sso W = sso.a("spotify:now-playing-view");
    public static final sso X = sso.a("spotify:now-playing-view-v2");
    public static final sso Y = sso.a("spotify:queue");
    public static final sso Z = sso.a("spotify:widget");
    public static final sso a = sso.a("spotify:main");
    public static final b aA;
    public static final b aB;
    public static final b aC;
    public static final sso aD = sso.a("spotify:create-playlist");
    public static final sso aE = sso.a("spotify:rename-playlist");
    public static final b aF;
    public static final b aG;
    public static final b aH = new b("spotify:user:[^:]+:folder:[a-fA-F0-9]{16}");
    public static final b aI = new b("spotify:album:[a-zA-Z0-9]{22}");
    public static final b aJ = new b("spotify:artist:[a-zA-Z0-9]{22}(:about|:albums|:singles|:appears_on|:appears-on|:compilations|:related|:releases|:biography|:gallery|:playlists|:radio|:concert|:concerts)?");
    public static final sso aK = sso.a("spotify:internal:preferences:facebook-connect");
    public static final sso aL = sso.a("spotify:add_to_playlist");
    public static final sso aM = sso.a("spotify:disk_almost_full");
    public static final sso aN = sso.a("spotify:debug");
    public static final sso aO = sso.a("spotify:quicksilver");
    public static final sso aP = sso.a("spotify:app:upsell");
    public static final sso aQ = sso.a("spotify:upsell:premium_in_app_destination");
    public static final sso aR = sso.a("spotify:premium:activation");
    public static final sso aS = sso.a("spotify:ads:screen_saver");
    public static final sso aT = sso.a("spotify:ads:marquee");
    public static final sso aU = sso.a("spotify:ads:leave_behind_companion");
    public static final sso aV = sso.a("spotify:internal:premium_signup");
    public static final sso aW = sso.a("spotify:app:share-flow");
    public static final sso aX = sso.a("spotify:app:share:facebook-stories");
    public static final sso aY = sso.a("spotify:app:share:instagram-stories");
    public static final sso aZ = sso.a("spotify:app:share:snapchat-stories");
    public static final sso aa = sso.a("spotify:app:concerts");
    public static final sso ab = sso.a("spotify:app:concerts:concert-group");
    public static final b ac = new b("spotify:concerts?:(songkick:events:)?[^:]+");
    public static final sso ad = sso.a("spotify:concerts:location-search");
    public static final sso ae = sso.a("spotify:find");
    public static final b af;
    public static final sso ag;
    public static final b ah = new b("spotify:search(:[^:]+)(:.+)");
    public static final b ai = new b("spotify:station:(artist:[a-zA-Z0-9]{22}|album:[a-zA-Z0-9]{22}|track:+[a-zA-Z0-9]{22}|genre:[^:]+|(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})|playlist:[a-zA-Z0-9]{22}|user:[^:]+:cluster:[a-zA-Z0-9]{22}|user:[^:]+:clusters|dailymix:[a-zA-Z0-9]{22})|spotify:dailymix:[a-zA-Z0-9]{22}");
    public static final b aj = new b("spotify:(artist:[a-zA-Z0-9]{22}|album:[a-zA-Z0-9]{22}|track:+[a-zA-Z0-9]{22}|genre:[^:]+|(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})|playlist:[a-zA-Z0-9]{22}|user:[^:]+:cluster:[a-zA-Z0-9]{22})");
    public static final b ak = new b("spotify:station:user:[^:]+:cluster:[a-zA-Z0-9]{22}");
    public static final b al = new b("spotify:station:user:[^:]+:clusters");
    public static final b am = new b("spotify:dailymix:[a-zA-Z0-9]{22}");
    public static final sso an = sso.a("spotify:daily-mix-hub");
    public static final sso ao = sso.a("spotify:made-for-you");
    public static final b ap = new b("spotify:station:artist:[a-zA-Z0-9]{22}");
    public static final b aq = new b("spotify:station:album:[a-zA-Z0-9]{22}");
    public static final b ar = new b("spotify:station:track:+[a-zA-Z0-9]{22}");
    public static final b as = new b("spotify:station:genre:[^:]+");
    public static final b at = new b("spotify:station:((user:[^:]+:)?(playlist:[a-zA-Z0-9]{22}))");
    public static final b au = new b("spotify:radio:artist:[a-zA-Z0-9]{22}");
    public static final b av = new b("spotify:radio:album:[a-zA-Z0-9]{22}");
    public static final b aw = new b("spotify:radio:track:+[a-zA-Z0-9]{22}");
    public static final b ax = new b("spotify:radio:genre:[^:]+");
    public static final b ay = new b("spotify:radio:((user:[^:]+:)?(playlist:[a-zA-Z0-9]{22}))");
    public static final b az = new b("spotify:user:[^:]+");
    public static final sso b = sso.a("spotify:listening-history");
    public static final sso bA = sso.a("spotify:internal:preferences:content_languages");
    public static final sso bB = sso.a("spotify:push_notification_actions");
    public static final sso bC = sso.a("spotify:internal:preferences:push_notification");
    public static final sso bD = sso.a("spotify:internal:local_files_import");
    public static final sso bE = sso.a("spotify:internal:local_files_import:folders");
    public static final sso bF = sso.a("spotify:internal:local_files_import:artists");
    public static final sso bG = sso.a("spotify:internal:local_files_import:albums");
    public static final sso bH = sso.a("spotify:internal:local_files_import:songs");
    public static final sso bI = sso.a("spotify:internal:notification");
    public static final sso bJ = sso.a("spotify:internal:preferences:storage");
    public static final sso bK = sso.a("spotify:config:account");
    public static final sso bL = sso.a("spotify:cover-image");
    public static final sso bM = sso.a("spotify:request-permissions");
    public static final sso bN = sso.a("spotify:app:app_rater");
    public static final sso bO = sso.a("spotify:media_service");
    public static final b bP = new b("spotify:show:[a-zA-Z0-9]{22}");
    public static final sso bQ = sso.a("spotify:speaker-companion:entity-feedback");
    public static final sso bR = sso.a("spotify:speaker-companion:page");
    public static final sso bS = sso.a("spotify:speaker-companion:banner");
    public static final sso bT = sso.a("spotify:datastories:wrapped");
    public static final sso bU = sso.a("spotify:voice-assistant");
    public static final sso bV = sso.a("spotify:voice-assistant:now-playing");
    public static final sso bW = sso.a("spotify:voice-assistant:dynamic_suggestion");
    public static final sso bX = sso.a("spotify:voice-assistant:onboarding");
    public static final sso bY = sso.a("spotify:voice-assistant:error");
    public static final sso bZ = sso.a("spotify:internal:service");
    public static final sso ba = sso.a("spotify:collection");
    public static final b bb = new b("spotify:user:[^:]+:collection");
    public static final sso bc = sso.a("spotify:internal:collection:playlists");
    public static final sso bd = sso.a("spotify:internal:collection:radio");
    public static final sso be = sso.a("spotify:internal:collection:artists");
    public static final sso bf = sso.a("spotify:internal:collection:albums");
    public static final b bg = new b("spotify:user:[^:]+:collection:album:[a-zA-Z0-9]{22}");
    public static final b bh = new b("spotify:user:[^:]+:collection:artist:[a-zA-Z0-9]{22}");
    public static final sso bi = sso.a("spotify:internal:collection:tracks");
    public static final sso bj = sso.a("spotify:internal:collection:offlined-music");
    public static final sso bk = sso.a("spotify:collection:podcasts:following");
    public static final sso bl = sso.a("spotify:collection:podcasts:episodes");
    public static final sso bm = sso.a("spotify:collection:podcasts:downloads");
    public static final sso bn = sso.a("spotify:internal:hidden-content");
    public static final sso bo = sso.a("spotify:internal:connect-device-picker");
    public static final sso bp = sso.a("spotify:internal:connect-device-context-menu");
    public static final sso bq = sso.a("spotify:internal:gaia-onboarding-popup");
    public static final sso br = sso.a("spotify:internal:gaia-popup");
    public static final sso bs = sso.a("spotify:internal:gaia-volume");
    public static final sso bt = sso.a("spotify:internal:connect-tutorial-desktop");
    public static final sso bu = sso.a("spotify:internal:connect-tutorial-speaker");
    public static final sso bv = sso.a("spotify:internal:connect-tutorial-tv");
    public static final sso bw = sso.a("spotify:internal:connect-tutorial-gameconsole");
    public static final sso bx = sso.a("spotify:internal:connect-tutorial-chromecast");
    public static final sso by = sso.a("spotify:internal:connect-tutorial-bluetooth");
    public static final sso bz = sso.a("spotify:internal:connect-tutorial-social-listening");
    public static final sso c = sso.a("spotify:app:radio");
    public static final sso ca = sso.a("spotify:internal:scannables");
    public static final sso cb = sso.a("spotify:socialsession:participant-list");
    public static final sso cc = sso.a("spotify:stations-promo");
    public static final sso cd = sso.a("spotify:podcastonboarding:topic-picker");
    public static final sso d = sso.a("spotify:startpage");
    public static final sso e = sso.a("spotify:home");
    public static final sso f = sso.a("spotify:fullscreen-story");
    public static final sso g = sso.a("spotify:internal:running");
    public static final sso h = sso.a("spotify:app:findfriends");
    public static final sso i = sso.a("spotify:findfriends:confirm");
    public static final sso j = sso.a("spotify:genre:podcasts-page");
    public static final sso k = sso.a("spotify:charts:root");
    public static final b l = new b("spotify:charts:[^:]+");
    public static final b m = new b("spotify:(app:)?chart:[^:]+");
    public static final b n;
    public static final b o;
    public static final b p;
    public static final b q;
    public static final b r;
    public static final sso s = sso.a("spotify:internal:startpage");
    public static final b t = new b("spotify:track:+[a-zA-Z0-9]{22}");
    public static final sso u = sso.a("spotify:driving:jumpstart");
    public static final sso v = sso.a("spotify:driving:pivot");
    public static final sso w = sso.a("spotify:driving:voice");
    public static final sso x = sso.a("spotify:car:lockscreen");
    public static final sso y = sso.a("spotify:waze:optout");
    public static final sso z = sso.a("spotify:waze:onboarding");

    @Deprecated
    public enum SubView {
        NONE(""),
        PLACEBO_BANNER("placebo-banner"),
        CANCEL_STATE_INTERSTITIAL("cancel_state_interstitial");
        
        private final String mSubView;

        private SubView(String str) {
            this.mSubView = (String) fbp.a(str);
        }

        public final String toString() {
            return this.mSubView;
        }
    }

    static {
        sso.a("spotify");
        sso.a("spotify:navigation");
        sso.a("spotify:playlists");
        new b("spotify:home:[^:]+");
        new b("spotify:(internal:)?running:[^:]+:[^:]+");
        sso.a("spotify:app:browse");
        StringBuilder sb = new StringBuilder("spotify:genre:[^:]+");
        String str = "(:[^:]++)?";
        sb.append(fbt.a(str, 4));
        n = new b(sb.toString());
        String str2 = "spotify:(app:)?browse";
        StringBuilder sb2 = new StringBuilder(str2);
        sb2.append(fbt.a(str, 5));
        o = new b(sb2.toString());
        p = new b(str2);
        String str3 = "spotify:special:[^:]+";
        q = new b(str3);
        StringBuilder sb3 = new StringBuilder(str3);
        sb3.append(fbt.a(str, 4));
        r = new b(sb3.toString());
        sso.a("spotify:free-tier:likes");
        sso.a("spotify:free-tier:likes:songs");
        sso.a("spotify:free-tier:profile");
        String str4 = "spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})";
        M = new b(str4);
        new b(str4);
        sso.a("spotify:free-tier:data-saver:learn-more");
        sso.a("spotify:free-tier:data-saver:opt-in-status");
        sso.a("spotify:internal:nft:education:favorites-mix");
        b bVar = new b("spotify:search(:.*)?");
        af = bVar;
        ag = bVar.a("spotify:search");
        aA = new b(str4);
        aB = new b(str4);
        aC = new b(str4);
        StringBuilder sb4 = new StringBuilder("spotify:internal:format_list_chart:(");
        sb4.append(aA);
        sb4.append(')');
        new b(sb4.toString());
        StringBuilder sb5 = new StringBuilder("spotify:internal:format_list_data_saver:(");
        sb5.append(aA);
        sb5.append(')');
        aF = new b(sb5.toString());
        StringBuilder sb6 = new StringBuilder("spotify:internal:format_list_personalized_sets:(");
        sb6.append(aA);
        sb6.append(')');
        aG = new b(sb6.toString());
        StringBuilder sb7 = new StringBuilder("spotify:internal:format_list_friends_weekly:(");
        sb7.append(aA);
        sb7.append(')');
        new b(sb7.toString());
        sso.a("spotify:intro:tos:text");
        sso.a("spotify:offline_sync_error");
        sso.a("spotify:upsell:choose_extreme_quality");
        sso.a("spotify:upsell:stuck_in_shuffle");
        sso.a("spotify:upsell:out_of_skips");
        String str5 = "spotify:upsell:no_offline";
        sso.a(str5);
        sso.a(str5);
        sso.a("spotify:upsell:no_queue");
        sso.a("spotify:upsell:trial-started");
        sso.a("spotify:upsell:trial-ended");
        sso.a("spotify:upsell:capping_reached");
        sso.a("spotify:upsell:content-unavailable");
        sso.a("spotify:ads:mobile_video_takeover");
        sso.a("spotify:ads:sponsored_session");
        sso.a("spotify:dynamic_upsell");
        sso.a("spotify:share");
        sso.a("spotify:share:missing-user");
        sso.a("spotify:licenses");
        sso.a("spotify:update");
        sso.a("spotify:internal:gaia-popup-account-linking");
        sso.a("spotify:internal:gaia-popup-dynamic-suggestion");
        sso.a("spotify:internal:preferences");
        sso.a("spotify:internal:tutorials");
        sso.a("spotify:churn_locked_state");
        sso.a("spotify:fullscreen_videoplayer");
        sso.a("spotify:wrapped:home");
        sso.a("spotify:podcastonboarding:send-topics");
    }
}
