package defpackage;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import com.comscore.android.id.IdHelperAndroid;
import com.comscore.util.crashreport.CrashReportManager;
import com.spotify.cosmos.bindings.BuildConfig;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@cey
/* renamed from: dsp reason: default package */
public final class dsp {
    public static final dsf<Long> A = dsf.a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final dsf<Boolean> B = dsf.a(1, "gads:video:aggressive_media_codec_release", Boolean.FALSE);
    public static final dsf<Boolean> C = dsf.a(1, "gads:memory_bundle:debug_info", Boolean.FALSE);
    public static final dsf<Boolean> D = dsf.a(1, "gads:memory_bundle:runtime_info", Boolean.TRUE);
    public static final dsf<String> E;
    public static final dsf<Integer> F = dsf.a(1, "gads:video:codec_query_minimum_version", 16);
    public static final dsf<Boolean> G = dsf.a(0, "gads:looper_for_gms_client:enabled", Boolean.TRUE);
    public static final dsf<Boolean> H = dsf.a(0, "gads:sw_ad_request_service:enabled", Boolean.TRUE);
    public static final dsf<String> I = dsf.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final dsf<String> J = dsf.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final dsf<String> K = dsf.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final dsf<String> L = dsf.a(1, "gad:mraid:version", "2.0");
    public static final dsf<Boolean> M = dsf.a(1, "gads:mraid:unload", Boolean.FALSE);
    public static final dsf<Boolean> N = dsf.a(0, "gads:enabled_sdk_csi", Boolean.FALSE);
    public static final dsf<String> O = dsf.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final dsf<Boolean> P = dsf.a(0, "gads:sdk_csi_write_to_file", Boolean.FALSE);
    public static final dsf<Boolean> Q = dsf.a(0, "gads:enable_content_fetching", Boolean.TRUE);
    public static final dsf<Integer> R = dsf.a(0, "gads:content_length_weight", 1);
    public static final dsf<Integer> S = dsf.a(0, "gads:content_age_weight", 1);
    public static final dsf<Integer> T = dsf.a(0, "gads:min_content_len", 11);
    public static final dsf<Integer> U = dsf.a(0, "gads:fingerprint_number", 10);
    public static final dsf<Integer> V = dsf.a(0, "gads:sleep_sec", 10);
    public static final dsf<Boolean> W = dsf.a(1, "gads:enable_content_url_hash", Boolean.TRUE);
    public static final dsf<Integer> X = dsf.a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final dsf<Boolean> Y = dsf.a(1, "gads:enable_content_vertical_hash", Boolean.TRUE);
    public static final dsf<Integer> Z = dsf.a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final dsf<String> a = dsf.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final dsf<Boolean> aA = dsf.a(0, "gads:webview:permission:disabled", Boolean.FALSE);
    public static final dsf<Boolean> aB = dsf.a(1, "gads:rewarded:adapter_initialization_enabled", Boolean.FALSE);
    public static final dsf<Long> aC = dsf.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final dsf<Boolean> aD = dsf.a(1, "gads:rewarded:ad_metadata_enabled", Boolean.FALSE);
    public static final dsf<Boolean> aE = dsf.a(1, "gads:app_activity_tracker:enabled", Boolean.TRUE);
    public static final dsf<Long> aF = dsf.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final dsf<Long> aG = dsf.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final dsf<Boolean> aH = dsf.a(1, "gads:adid_values_in_adrequest:enabled", Boolean.FALSE);
    public static final dsf<Long> aI = dsf.a(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final dsf<Boolean> aJ = dsf.a(1, "gads:disable_adid_values_in_ms", Boolean.FALSE);
    public static final dsf<Boolean> aK = dsf.a(1, "gads:enable_ad_loader_manager", Boolean.TRUE);
    public static final dsf<Boolean> aL = dsf.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.TRUE);
    public static final dsf<Boolean> aM = dsf.a(1, "gads:ad_manager:admob_extra:new_bundle", Boolean.TRUE);
    public static final dsf<Long> aN = dsf.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final dsf<Boolean> aO = dsf.a(1, "gads:interstitial_ad_immersive_mode", Boolean.TRUE);
    public static final dsf<Boolean> aP = dsf.a(1, "gads:custom_close_blocking:enabled", Boolean.FALSE);
    public static final dsf<Boolean> aQ = dsf.a(1, "gads:disabling_closable_area:enabled", Boolean.FALSE);
    public static final dsf<Boolean> aR = dsf.a(1, "gads:interstitial_ad_pool:enabled", Boolean.FALSE);
    public static final dsf<Boolean> aS = dsf.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.FALSE);
    public static final dsf<String> aT = dsf.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final dsf<String> aU = dsf.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final dsf<Integer> aV = dsf.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final dsf<Integer> aW = dsf.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final dsf<Integer> aX = dsf.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final dsf<String> aY;
    public static final dsf<Integer> aZ = dsf.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final dsf<Integer> aa = dsf.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final dsf<String> ab = dsf.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final dsf<String> ac = dsf.a(1, "gads:content_fetch_exclude_view_tag", IdHelperAndroid.NO_ID_AVAILABLE);
    public static final dsf<Boolean> ad = dsf.a(0, "gad:app_index_enabled", Boolean.TRUE);
    public static final dsf<Boolean> ae = dsf.a(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.FALSE);
    public static final dsf<Boolean> af = dsf.a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.TRUE);
    public static final dsf<Boolean> ag = dsf.a(0, "gads:interstitial_follow_url", Boolean.TRUE);
    public static final dsf<Boolean> ah = dsf.a(0, "gads:interstitial_follow_url:register_click", Boolean.TRUE);
    public static final dsf<Boolean> ai = dsf.a(0, "gads:ad_key_enabled", Boolean.FALSE);
    public static final dsf<Boolean> aj = dsf.a(1, "gads:sai:enabled", Boolean.TRUE);
    public static final dsf<Boolean> ak = dsf.a(1, "gads:sai:banner_ad_enabled", Boolean.TRUE);
    public static final dsf<Boolean> al = dsf.a(1, "gads:sai:native_ad_enabled", Boolean.TRUE);
    public static final dsf<Boolean> am = dsf.a(1, "gads:sai:interstitial_ad_enabled", Boolean.TRUE);
    public static final dsf<Boolean> an = dsf.a(1, "gads:sai:rewardedvideo_ad_enabled", Boolean.TRUE);
    public static final dsf<String> ao = dsf.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final dsf<String> ap = dsf.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final dsf<Boolean> aq = dsf.a(1, "gads:sai:click_gmsg_enabled", Boolean.TRUE);
    public static final dsf<Boolean> ar = dsf.a(1, "gads:sai:using_macro:enabled", Boolean.FALSE);
    public static final dsf<String> as = dsf.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final dsf<Long> at = dsf.a(1, "gads:sai:timeout_ms", -1);
    public static final dsf<Integer> au = dsf.a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final dsf<Boolean> av = dsf.a(1, "gads:x_seconds_rewarded:enable", Boolean.FALSE);
    public static final dsf<Boolean> aw = dsf.a(1, "gads:webview:ignore_over_scroll", Boolean.TRUE);
    public static final dsf<Boolean> ax = dsf.a(0, "gads:corewebview:adwebview_factory:enable", Boolean.FALSE);
    public static final dsf<Boolean> ay = dsf.a(0, "gads:corewebview:javascript_engine", Boolean.FALSE);
    public static final dsf<Boolean> az = dsf.a(1, "gad:webview:inject_scripts", Boolean.FALSE);
    public static final dsf<Boolean> b = dsf.a(0, "gads:sdk_crash_report_enabled", Boolean.FALSE);
    public static final dsf<Boolean> bA = dsf.a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.FALSE);
    public static final dsf<Long> bB = dsf.a(1, "gads:gestures:task_timeout", 2000);
    public static final dsf<Boolean> bC = dsf.a(1, "gads:gestures:asig:enabled", Boolean.FALSE);
    public static final dsf<Boolean> bD = dsf.a(1, "gads:gestures:ans:enabled", Boolean.FALSE);
    public static final dsf<Boolean> bE = dsf.a(1, "gads:gestures:tos:enabled", Boolean.FALSE);
    public static final dsf<Boolean> bF = dsf.a(1, "gads:signal:app_permissions:disabled", Boolean.FALSE);
    public static final dsf<Boolean> bG = dsf.a(1, "gads:gestures:inthex:enabled", Boolean.FALSE);
    public static final dsf<Boolean> bH = dsf.a(1, "gads:gestures:hpk:enabled", Boolean.TRUE);
    public static final dsf<String> bI;
    public static final dsf<Boolean> bJ = dsf.a(1, "gads:gestures:bs:enabled", Boolean.TRUE);
    public static final dsf<Boolean> bK = dsf.a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.FALSE);
    public static final dsf<Boolean> bL = dsf.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.TRUE);
    public static final dsf<Boolean> bM = dsf.a(0, "gass:enabled", Boolean.TRUE);
    public static final dsf<Boolean> bN = dsf.a(0, "gass:enable_int_signal", Boolean.TRUE);
    public static final dsf<Boolean> bO = dsf.a(0, "gass:enable_ad_attestation_signal", Boolean.TRUE);
    public static final dsf<Boolean> bP = dsf.a(0, "gads:support_screen_shot", Boolean.TRUE);
    public static final dsf<Boolean> bQ = dsf.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.TRUE);
    public static final dsf<String> bR;
    public static final dsf<Long> bS = dsf.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final dsf<Boolean> bT = dsf.a(0, "gads:js_flags:mf", Boolean.FALSE);
    public static final dsf<Boolean> bU = dsf.a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.FALSE);
    public static final dsf<String> bV = dsf.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final dsf<String> bW = dsf.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final dsf<Boolean> bX = dsf.a(1, "gads:enable_untrack_view_native", Boolean.TRUE);
    public static final dsf<Boolean> bY = dsf.a(1, "gads:ignore_untrack_view_google_native", Boolean.TRUE);
    public static final dsf<Boolean> bZ = dsf.a(1, "gads:reset_listeners_preparead_native", Boolean.TRUE);
    public static final dsf<Integer> ba = dsf.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final dsf<Long> bb = dsf.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final dsf<Long> bc = dsf.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final dsf<Float> bd = dsf.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final dsf<Float> be = dsf.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final dsf<Boolean> bf = dsf.a(0, "gads:debug_logging_feature:enable", Boolean.FALSE);
    public static final dsf<Boolean> bg = dsf.a(0, "gads:debug_logging_feature:intercept_web_view", Boolean.FALSE);
    public static final dsf<String> bh;
    public static final dsf<String> bi;
    public static final dsf<Boolean> bj = dsf.a(0, "gads:log:verbose_enabled", Boolean.FALSE);
    public static final dsf<Boolean> bk = dsf.a(1, "gads:include_local_global_rectangles", Boolean.FALSE);
    public static final dsf<Long> bl = dsf.a(1, "gads:position_watcher:throttle_ms", 200);
    public static final dsf<Boolean> bm = dsf.a(1, "gads:include_lock_screen_apps_for_visibility", Boolean.TRUE);
    public static final dsf<Boolean> bn = dsf.a(0, "gads:device_info_caching:enabled", Boolean.TRUE);
    public static final dsf<Long> bo = dsf.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final dsf<Boolean> bp = dsf.a(1, "gads:gen204_signals:enabled", Boolean.FALSE);
    public static final dsf<Boolean> bq = dsf.a(0, "gads:webview:error_reporting_enabled", Boolean.FALSE);
    public static final dsf<Boolean> br = dsf.a(1, "gads:gmsg:disable_back_button:enabled", Boolean.TRUE);
    public static final dsf<Boolean> bs = dsf.a(0, "gads:gmsg:video_meta:enabled", Boolean.TRUE);
    public static final dsf<Long> bt = dsf.a(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final dsf<Boolean> bu = dsf.a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.TRUE);
    public static final dsf<Boolean> bv = dsf.a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.TRUE);
    public static final dsf<Boolean> bw = dsf.a(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.TRUE);
    public static final dsf<Long> bx = dsf.a(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final dsf<Long> by = dsf.a(0, "gads:ad_loader:timeout_ms", 60000);
    public static final dsf<Long> bz = dsf.a(0, "gads:rendering:timeout_ms", 60000);
    public static final dsf<Boolean> c = dsf.a(0, "gads:report_dynamite_crash_in_background_thread", Boolean.FALSE);
    public static final dsf<Boolean> cA = dsf.a(0, "gads:webview_cookie:enabled", Boolean.TRUE);
    public static final dsf<Boolean> cB = dsf.a(1, "gads:cache:bind_on_foreground", Boolean.FALSE);
    public static final dsf<Boolean> cC = dsf.a(1, "gads:cache:bind_on_init", Boolean.FALSE);
    public static final dsf<Boolean> cD = dsf.a(1, "gads:cache:bind_on_request", Boolean.FALSE);
    public static final dsf<Long> cE = dsf.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final dsf<Boolean> cF = dsf.a(1, "gads:cache:use_cache_data_source", Boolean.FALSE);
    public static final dsf<Boolean> cG = dsf.a(1, "gads:http_assets_cache:enabled", Boolean.FALSE);
    public static final dsf<String> cH = dsf.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final dsf<Integer> cI = dsf.a(1, "gads:http_assets_cache:time_out", 100);
    public static final dsf<Boolean> cJ = dsf.a(1, "gads:chrome_custom_tabs:enabled", Boolean.TRUE);
    public static final dsf<Boolean> cK = dsf.a(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.FALSE);
    public static final dsf<Boolean> cL = dsf.a(1, "gads:chrome_custom_tabs:disabled", Boolean.FALSE);
    public static final dsf<Boolean> cM = dsf.a(1, "gads:drx_in_app_preview:enabled", Boolean.TRUE);
    public static final dsf<Boolean> cN = dsf.a(1, "gads:drx_debug_signals:enabled", Boolean.TRUE);
    public static final dsf<Boolean> cO = dsf.a(1, "gads:debug_hold_gesture:enabled", Boolean.FALSE);
    public static final dsf<Long> cP = dsf.a(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final dsf<String> cQ = dsf.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final dsf<String> cR = dsf.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final dsf<String> cS = dsf.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final dsf<String> cT = dsf.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final dsf<Integer> cU = dsf.a(1, "gads:drx_debug:timeout_ms", (int) CrashReportManager.TIME_WINDOW);
    public static final dsf<Integer> cV = dsf.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final dsf<Boolean> cW = dsf.a(1, "gad:interstitial_for_multi_window", Boolean.FALSE);
    public static final dsf<Boolean> cX = dsf.a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.FALSE);
    public static final dsf<Integer> cY = dsf.a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final dsf<Boolean> cZ = dsf.a(1, "gads:clearcut_logging:enabled", Boolean.FALSE);
    public static final dsf<Integer> ca = dsf.a(1, "gads:native_video_load_timeout", 10);
    public static final dsf<Integer> cb = dsf.a(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final dsf<String> cc = dsf.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final dsf<Boolean> cd = dsf.a(1, "gads:clamp_native_video_player_dimensions", Boolean.TRUE);
    public static final dsf<Boolean> ce = dsf.a(1, "gads:enable_store_active_view_state", Boolean.FALSE);
    public static final dsf<Boolean> cf = dsf.a(1, "gads:enable_singleton_broadcast_receiver", Boolean.FALSE);
    public static final dsf<Boolean> cg = dsf.a(1, "gads:native:overlay_new_fix:enabled", Boolean.TRUE);
    public static final dsf<Boolean> ch = dsf.a(1, "gads:native:count_impression_for_assets", Boolean.FALSE);
    public static final dsf<Boolean> ci = dsf.a(1, "gads:native:custom_one_point_five_click:enable", Boolean.TRUE);
    public static final dsf<Boolean> cj = dsf.a(1, "gads:unified_native_ad:enable", Boolean.TRUE);
    public static final dsf<Boolean> ck = dsf.a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.FALSE);
    public static final dsf<Boolean> cl = dsf.a(0, "gads:method_tracing:enabled", Boolean.FALSE);
    public static final dsf<Long> cm = dsf.a(0, "gads:method_tracing:duration_ms", 30000);
    public static final dsf<Integer> cn = dsf.a(0, "gads:method_tracing:count", 5);
    public static final dsf<Integer> co = dsf.a(0, "gads:method_tracing:filesize", 134217728);
    public static final dsf<Long> cp = dsf.a(1, "gads:auto_location_timeout", 2000);
    public static final dsf<Boolean> cq = dsf.a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.FALSE);
    public static final dsf<Long> cr = dsf.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final dsf<String> cs = dsf.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final dsf<String> ct = dsf.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final dsf<String> cu = dsf.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final dsf<String> cv = dsf.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final dsf<String> cw = dsf.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final dsf<Long> cx = dsf.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final dsf<Long> cy = dsf.a(1, "gads:parental_controls:timeout", 2000);
    public static final dsf<Boolean> cz = dsf.a(0, "gads:safe_browsing:debug", Boolean.FALSE);
    public static final dsf<Boolean> d = dsf.a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.FALSE);
    public static final dsf<Boolean> da = dsf.a(1, "gads:clearcut_logging:write_to_file", Boolean.FALSE);
    public static final dsf<Boolean> db = dsf.a(0, "gad:force_local_ad_request_service:enabled", Boolean.FALSE);
    public static final dsf<Boolean> dc = dsf.a(0, "gad:force_dynamite_loading_enabled", Boolean.FALSE);
    public static final dsf<Integer> dd = dsf.a(1, "gad:http_redirect_max_count:times", 8);
    public static final dsf<Boolean> de = dsf.a(1, "gads:omid:enabled", Boolean.FALSE);
    public static final dsf<Boolean> df = dsf.a(1, "gads:nonagon:banner:check_dp_size", Boolean.FALSE);
    public static final dsf<Long> dg = dsf.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final dsf<String> dh = dsf.a(0, "gads:public_beta:traffic_multiplier", BuildConfig.VERSION_NAME);
    public static final dsf<Boolean> di = dsf.a(1, "gads:real_test_request:enabled", Boolean.TRUE);
    public static final dsf<Boolean> dj = dsf.a(1, "gads:real_test_request:render_webview_label", Boolean.TRUE);
    public static final dsf<Boolean> dk = dsf.a(1, "gads:real_test_request:render_native_label", Boolean.TRUE);
    public static final dsf<Integer> dl = dsf.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final dsf<Integer> dm = dsf.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final dsf<Integer> dn = dsf.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);

    /* renamed from: do reason: not valid java name */
    public static final dsf<Integer> f8do = dsf.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static final dsf<Integer> dp = dsf.a(1, "gads:heap_wastage:bytes", 0);
    public static final dsf<String> e = dsf.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final dsf<Float> f = dsf.a(1, "gads:trapped_exception_sample_rate", 0.01f);
    public static final dsf<Boolean> g = dsf.a(0, "gads:block_autoclicks", Boolean.FALSE);
    public static final dsf<String> h = dsf.a(1, "gads:video_exo_player:version", "1");
    public static final dsf<Integer> i = dsf.a(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final dsf<Integer> j = dsf.a(1, "gads:video_exo_player:read_timeout", 8000);
    public static final dsf<Integer> k = dsf.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final dsf<Integer> l = dsf.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final dsf<Integer> m = dsf.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final dsf<Integer> n = dsf.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final dsf<Integer> o = dsf.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final dsf<Integer> p = dsf.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final dsf<Long> q = dsf.a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final dsf<Long> r = dsf.a(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final dsf<Integer> s = dsf.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final dsf<Boolean> t = dsf.a(0, "gads:video:metric_reporting_enabled", Boolean.FALSE);
    public static final dsf<String> u;
    public static final dsf<Long> v = dsf.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final dsf<Boolean> w = dsf.a(1, "gads:video:force_watermark", Boolean.FALSE);
    public static final dsf<Long> x = dsf.a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final dsf<Boolean> y = dsf.a(1, "gads:video:spinner:enabled", Boolean.FALSE);
    public static final dsf<Integer> z = dsf.a(1, "gads:video:spinner:scale", 4);

    static {
        dsf.a(0, "gads:sdk_core_experiment_id");
        dsf.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
        dsf.a(0, "gads:request_builder:singleton_webview", Boolean.FALSE);
        dsf.a(0, "gads:request_builder:singleton_webview_experiment_id");
        dsf.a(0, "gads:sdk_use_dynamic_module", Boolean.TRUE);
        dsf.a(0, "gads:sdk_use_dynamic_module_experiment_id");
        dsf.a(0, "gads:block_autoclicks_experiment_id");
        dsf.a(0, "gads:spam_app_context:experiment_id");
        dsf.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
        dsf.a(0, "gads:video_stream_cache:experiment_id");
        String str = "";
        u = dsf.a(1, "gads:video:metric_frame_hash_times", str);
        E = dsf.a(1, "gads:video:codec_query_mime_types", str);
        dsf.a(0, "gads:ad_id_app_context:enabled", Boolean.FALSE);
        dsf.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
        dsf.a(0, "gads:ad_id_app_context:experiment_id");
        dsf.a(0, "gads:ad_id_use_shared_preference:experiment_id");
        dsf.a(0, "gads:ad_id_use_shared_preference:enabled", Boolean.FALSE);
        dsf.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
        dsf.a(0, "gads:ad_id_use_persistent_service:enabled", Boolean.FALSE);
        dsf.a(0, "gads:ad_id:use_ipc:enabled", Boolean.FALSE);
        dsf.b(0, "gads:looper_for_gms_client:experiment_id");
        dsf.a(0, "gads:sw_dynamite:enabled", Boolean.TRUE);
        dsf.a(0, "gads:app_index:without_content_info_present:enabled", Boolean.TRUE);
        dsf.a(0, "gads:app_index:timeout_ms", 1000);
        dsf.a(0, "gads:app_index:experiment_id");
        dsf.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
        dsf.a(0, "gads:interstitial_follow_url:experiment_id");
        dsf.a(0, "gads:analytics_enabled", Boolean.TRUE);
        dsf.a(0, "gads:webview_cache_version", 0);
        dsf.b(0, "gads:pan:experiment_id");
        dsf.a(0, "gads:ad_serving:enabled", Boolean.TRUE);
        dsf.a(1, "gads:impression_optimization_enabled", Boolean.FALSE);
        dsf.a(1, "gads:banner_ad_pool:schema", "customTargeting");
        dsf.a(1, "gads:banner_ad_pool:max_queues", 3);
        dsf.a(1, "gads:banner_ad_pool:max_pools", 3);
        String str2 = "(?!)";
        aY = dsf.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", str2);
        bh = dsf.a(1, "gads:spherical_video:vertex_shader", str);
        bi = dsf.a(1, "gads:spherical_video:fragment_shader", str);
        dsf.a(0, "gads:adid_reporting:enabled", Boolean.FALSE);
        dsf.a(0, "gads:ad_settings_page_reporting:enabled", Boolean.FALSE);
        dsf.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.FALSE);
        dsf.a(0, "gads:request_pkg:enabled", Boolean.TRUE);
        dsf.a(0, "gads:gmsg:video_meta:experiment_id");
        dsf.a(1, "gads:network:cache_prediction_duration_s", 300);
        dsf.a(1, "gads:rtb_signal_timeout_ms", 1000);
        bI = dsf.a(1, "gads:gestures:pk", str);
        dsf.a(0, "gads:adid_notification:first_party_check:enabled", Boolean.TRUE);
        dsf.a(0, "gads:edu_device_helper:enabled", Boolean.TRUE);
        dsf.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
        dsf.a(1, "gads:sdk_core_constants:experiment_id");
        bR = dsf.a(1, "gads:sdk_core_constants:caps", str);
        dsf.a(1, "gads:js_flags:disable_phenotype", Boolean.FALSE);
        dsf.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
        dsf.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
        dsf.a(1, "gads:singleton_webview_native:experiment_id");
        dsf.a(1, "gads:auto_location_for_coarse_permission", Boolean.FALSE);
        dsf.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
        dsf.b(1, "gads:auto_location_timeout:experiment_id");
        dsf.a(1, "gads:auto_location_interval", -1);
        dsf.b(1, "gads:auto_location_interval:experiment_id");
        dsf.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        dsf.a(0, "gads:afs:csa:experiment_id");
        dsf.a(0, "gads:afs:csa_ad_manager_enabled", Boolean.TRUE);
        dsf.a(1, "gads:parental_controls:send_from_client", Boolean.TRUE);
        dsf.a(1, "gads:parental_controls:cache_results", Boolean.TRUE);
        dsf.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        dsf.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
        dsf.a(1, "gads:cache:ad_request_timeout_millis", 250);
        dsf.a(1, "gads:cache:max_concurrent_downloads", 10);
        dsf.a(1, "gads:cache:javascript_timeout_millis", 5000);
        dsf.a(1, "gads:cache:connection_per_read", Boolean.FALSE);
        dsf.a(1, "gads:cache:connection_timeout", 5000);
        dsf.a(1, "gads:cache:read_only_connection_timeout", 5000);
        dsf.a(0, "gads:nonagon:red_button", Boolean.FALSE);
        dsf.a(1, "gads:nonagon:banner:enabled", Boolean.FALSE);
        dsf.a(1, "gads:nonagon:banner:ad_unit_exclusions", str2);
        dsf.a(1, "gads:nonagon:interstitial:enabled", Boolean.FALSE);
        dsf.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", str2);
        dsf.a(1, "gads:nonagon:rewardedvideo:enabled", Boolean.FALSE);
        dsf.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.FALSE);
        dsf.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", str2);
        dsf.a(1, "gads:nonagon:nativead:enabled", Boolean.FALSE);
        dsf.a(1, "gads:nonagon:nativead:app_name", str2);
        dsf.a(1, "gads:nonagon:service:enabled", Boolean.FALSE);
        dsf.a(1, "gads:signals:ad_id_info:enabled", Boolean.FALSE);
        dsf.a(1, "gads:signals:app_index:enabled", Boolean.FALSE);
        dsf.a(1, "gads:signals:cache:enabled", Boolean.FALSE);
        dsf.a(1, "gads:signals:doritos:enabled", Boolean.FALSE);
        dsf.a(1, "gads:signals:location:enabled", Boolean.FALSE);
        dsf.a(1, "gads:signals:network_prediction:enabled", Boolean.FALSE);
        dsf.a(1, "gads:signals:parental_control:enabled", Boolean.FALSE);
    }

    public static List<String> a() {
        return dpn.e().a();
    }

    public static void a(Context context) {
        cod.a(context, new dsq(context));
        ((Integer) dpn.f().a(dp)).intValue();
    }

    public static void a(Context context, JSONObject jSONObject) {
        dpn.d();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        dpn.e().a(edit, jSONObject);
        dpn.d();
        edit.commit();
    }

    public static List<String> b() {
        dsl e2 = dpn.e();
        List<String> a2 = e2.a();
        for (dsf a3 : e2.c) {
            String str = (String) dpn.f().a(a3);
            if (str != null) {
                a2.add(str);
            }
        }
        return a2;
    }
}
