package defpackage;

/* renamed from: gni reason: default package */
final class gni {
    /* JADX WARNING: Code restructure failed: missing block: B:9:0x005a, code lost:
        return 0;
     */
    /* JADX WARNING: Removed duplicated region for block: B:10:? A[ExcHandler: IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException (unused java.lang.Throwable), SYNTHETIC, Splitter:B:5:0x0016] */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    static long a() {
        /*
            java.lang.String r0 = "_SC_CLK_TCK"
            r1 = 0
            r2 = 0
            java.lang.String r4 = "android.system.OsConstants"
            java.lang.Class r4 = java.lang.Class.forName(r4)     // Catch:{ ClassNotFoundException -> 0x0014 }
            java.lang.reflect.Field r4 = r4.getField(r0)     // Catch:{ ClassNotFoundException -> 0x0014 }
            int r0 = r4.getInt(r1)     // Catch:{ ClassNotFoundException -> 0x0014 }
            goto L_0x0022
        L_0x0014:
            java.lang.String r4 = "libcore.io.OsConstants"
            java.lang.Class r4 = java.lang.Class.forName(r4)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.reflect.Field r0 = r4.getField(r0)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            int r0 = r0.getInt(r1)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
        L_0x0022:
            java.lang.String r4 = "libcore.io.Libcore"
            java.lang.Class r4 = java.lang.Class.forName(r4)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.String r5 = "os"
            java.lang.reflect.Field r4 = r4.getField(r5)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.Object r1 = r4.get(r1)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.Class r4 = r1.getClass()     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.String r5 = "sysconf"
            r6 = 1
            java.lang.Class[] r7 = new java.lang.Class[r6]     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.Class r8 = java.lang.Integer.TYPE     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            r9 = 0
            r7[r9] = r8     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.reflect.Method r4 = r4.getMethod(r5, r7)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.Object[] r5 = new java.lang.Object[r6]     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.Integer r0 = java.lang.Integer.valueOf(r0)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            r5[r9] = r0     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.Object r0 = r4.invoke(r1, r5)     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            java.lang.Long r0 = (java.lang.Long) r0     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            long r0 = r0.longValue()     // Catch:{ IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a, IllegalAccessException | NoSuchFieldException | NoSuchMethodException | InvocationTargetException -> 0x005a }
            r4 = 1000(0x3e8, double:4.94E-321)
            long r4 = r4 / r0
            return r4
        L_0x005a:
            return r2
        */
        throw new UnsupportedOperationException("Method not decompiled: defpackage.gni.a():long");
    }
}
