package com.spotify.mobile.android.sso;

public enum ErrorMessage {
    INVALID_VERSION_ERROR("INVALID_VERSION", ErrorType.INVALID_REQUEST),
    INVALID_PARAMETERS_ERROR(r3, ErrorType.INVALID_REQUEST),
    c(r6, ErrorType.UNRECOVERABLE),
    d(r7, ErrorType.RECOVERABLE),
    e(r8, ErrorType.RECOVERABLE),
    BAKERY_REQUEST_ERROR("INTERNAL_ERROR", ErrorType.RECOVERABLE),
    g(r10, ErrorType.RECOVERABLE),
    ACCOUNTS_SERVICE_ERROR("AUTHENTICATION_SERVICE_UNAVAILABLE", ErrorType.UNRECOVERABLE),
    UNKNOWN_RESPONSE_TYPE_ERROR("INVALID_RESPONSE", ErrorType.INVALID_REQUEST),
    CLIENT_VERIFICATION_ERROR("CLIENT_VERIFICATION_FAILED", ErrorType.INVALID_REQUEST),
    ACCOUNTS_INVALID_CLIENT("INVALID_CLIENT", ErrorType.INVALID_REQUEST),
    ACCOUNTS_INVALID_APP_ID("INVALID_APP_ID", ErrorType.INVALID_REQUEST),
    ACCOUNTS_INVALID_REQUEST(r3, ErrorType.INVALID_REQUEST),
    ACCOUNTS_UNKNOWN_ERROR("AUTHENTICATION_SERVICE_UNKNOWN_ERROR", ErrorType.UNRECOVERABLE),
    ACCOUNTS_USER_DENIED("AUTHENTICATION_DENIED_BY_USER", ErrorType.UNRECOVERABLE),
    CANCELLED("CANCELLED", ErrorType.UNRECOVERABLE),
    NEEDS_AUTHORIZATION_ERROR("USER_AUTHORIZATION_REQUIRED", ErrorType.UNRECOVERABLE);
    
    public final ErrorType mErrorType;
    public final String mMessage;

    private ErrorMessage(String str, ErrorType errorType) {
        this.mMessage = str;
        this.mErrorType = errorType;
    }
}
